name: CI
on:
  workflow_call:
    inputs:
      trigger:
        required: false
        type: string
        default: "merge_group"
  push:
    branches:
      - staging
      - trying
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  merge_group:

jobs:
  skip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
    outputs:
      skip-check: ${{ steps.skipper.outputs.skip-check }}
    steps:
      - uses: actions/checkout@v6
        if: github.event_name == 'merge_group'
      - id: skipper
        if: github.event_name == 'merge_group'
        uses: ./.github/actions/merge-queue-ci-skipper
      - name: Log skip decision
        run: |
          echo "event: ${{ github.event_name }}"
          echo "skip-check: ;${{ steps.skipper.outputs.skip-check }};"

  lint-ci:
    needs: skip
    if: needs.skip.outputs.skip-check != 'true'
    uses: ./.github/workflows/lint.yml

  helm-ci:
    needs: skip
    if: needs.skip.outputs.skip-check != 'true'
    uses: ./.github/workflows/helm.yml
    secrets: inherit
    with:
      trigger: ${{  inputs.trigger == 'try' && 'try' ||  startsWith(github.head_ref, 'mergify/merge-queue/') && 'merge_group' ||  github.event_name}}

  k8s-ci:
    needs: skip
    if: needs.skip.outputs.skip-check != 'true'
    uses: ./.github/workflows/k8s-ci.yml
    secrets: inherit

  ci:
    if: needs.skip.outputs.skip-check != 'true'
    needs:
      - skip
      - lint-ci
      - helm-ci
      - k8s-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: |
          echo "skip-check: ;${{ needs.skip.outputs.skip-check }};"
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
