name: CI
on:
  workflow_call:
    inputs:
      trigger:
        required: false
        type: string
        default: "merge_group"
  push:
    branches:
      - staging
      - trying
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  merge_group:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log event name
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "trigger: ;${{ inputs.trigger }};"
          echo "$GITHUB_CONTEXT"

  lint-ci:
    if: github.event_name == 'pull_request' && inputs.trigger != 'try'
    uses: ./.github/workflows/lint.yml

  helm-ci:
    uses: ./.github/workflows/helm.yml
    secrets: inherit
    with:
      trigger: ${{ github.event_name }}

  k8s-ci:
    if: github.event_name != 'pull_request' || startsWith(github.head_ref, 'mergify/merge-queue/')
    uses: ./.github/workflows/k8s-ci.yml
    secrets: inherit

  ci:
    if: ${{ !cancelled() && (github.event_name != 'pull_request' || startsWith(github.head_ref, 'mergify/merge-queue/')) }}
    needs:
      - lint-ci
      - helm-ci
      - k8s-ci
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
