name: Linter

on:
  workflow_call:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log event name
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: PR lint step
        run: echo "Running PR lint checks"
