name: Merge Queue Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

permissions:
  contents: 'read'

jobs:
  pr-lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PR lint step
        run: echo "Running PR lint checks"

  pr-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PR test step
        run: echo "Running PR tests"


  merge_queue_skipper:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    outputs:
      skip: '${{ steps.merge-queue-ci-skipper.outputs.skip-check }}'
    steps:
      - uses: actions/checkout@v6
      - id: 'merge-queue-ci-skipper'
        uses: ./.github/actions/merge-queue-ci-skipper
        with:
          secret: ${{ secrets.MERGE_Q_SKIPPER }}
          exclude-checks: merge-queue-integration

  merge-queue-validate:
    needs: [ merge_queue_skipper ]
    if: >
      !cancelled() && (
        github.event_name == 'pull_request' ||
        (github.event_name == 'merge_group' && needs.merge_queue_skipper.outputs.skip != 'true')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Fail if merge_queue_skipper failed
        if: needs.merge_queue_skipper.result == 'failure'
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge queue validation step
        run: echo "Running merge queue validation"

  merge-queue-integration:
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge queue integration step
        run: echo "Running merge queue integration checks"
      - run: sleep 30

  ci:
    needs:
      - merge_queue_skipper
      - merge-queue-validate
      - merge-queue-integration
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          exit 0
