name: Merge Queue Test

on:
  merge_group:
    types: [checks_requested]

permissions:
  contents: 'read'

jobs:
  merge-q-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PR lint step
        run: echo "Running PR lint checks"

